version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=your-claim
    volumes:
      - ./config:/config
      - /path/to/your/music/library:/musics:ro
    restart: unless-stopped
    mem_limit: 700m
    memswap_limit: 2000m
    devices:
      - /dev/dri:/dev/dri #optional
    ports:
      - 32400:32400
